In [5]:
import pandas as pd
df = pd.DataFrame([], columns=['pubcode', '日期', '链接', '备注'], index=['pubcode'])
df

        pubcode   日期   链接   备注
pubcode     NaN  NaN  NaN  NaN

In [8]:
df = pd.DataFrame([], columns=['pubcode', '日期', '链接', '备注'], index=['1'])
df

  pubcode   日期   链接   备注
1     NaN  NaN  NaN  NaN